[[ISSUERS]]
address = "rG36YtgpGPc6HRqmmF4eP2xA5oSMJqz1MP"
name = "WOJAK XRP"

[[TOKENS]]
issuer = "rG36YtgpGPc6HRqmmF4eP2xA5oSMJqz1MP"
currency = "WOJAK"
name = "WOJAK XRP"
desc = ""
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://google.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://youtube.com"
type = "website"
title = "Token Info Dashboard"

[[TOKENS.WEBLINKS]]
url = "https://twitter.com"
type = "socialmedia"
