[[ISSUERS]]
address = "ra4vn27zu6Gt11vGqeWzqehvHmmAWGBqix"
name = "BRUVA"

[[TOKENS]]
issuer = "ra4vn27zu6Gt11vGqeWzqehvHmmAWGBqix"
currency = "BRUVA"
name = "BRUV CTO"
desc = "BRUV CTO"
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://google.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://youtube.com"
type = "website"
title = "Token Info Dashboard"

[[TOKENS.WEBLINKS]]
url = "https://twitter.com"
type = "socialmedia"
