[[ISSUERS]]
address = "rHuF1wgdbVPDXE3DiDrxEUp3H3JVpCLcGx"
name = "HEXRP AI"

[[TOKENS]]
issuer = "rHuF1wgdbVPDXE3DiDrxEUp3H3JVpCLcGx"
currency = "HEXRP"
name = "HEXRP AI"
desc = "HEXRP AI"
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://google.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://youtube.com"
type = "website"
title = "Token Info Dashboard"

[[TOKENS.WEBLINKS]]
url = "https://twitter.com"
type = "socialmedia"
