[[ISSUERS]]
address = "r3ivFn8XeSfbWRCDqHQW2BPDYRJ1yUXYaR"
name = "MAGA"

[[TOKENS]]
issuer = "r3ivFn8XeSfbWRCDqHQW2BPDYRJ1yUXYaR"
currency = "MAGA"
name = "MAGA"
desc = "ITS JUST MAGA 25"
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://google.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://youtube.com"
type = "website"
title = "Token Info Dashboard"

[[TOKENS.WEBLINKS]]
url = "https://twitter.com"
type = "socialmedia"
