[[ISSUERS]]
address = "r3zCxvBEzGJ9ZjVoy4ikKiBNya5UHHLXbw"

[[TOKENS]]
issuer = "r3zCxvBEzGJ9ZjVoy4ikKiBNya5UHHLXbw"
currency = "BBRUV"
name = "BABY BRUV"
desc = "BABY BRUV"
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://google.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://youtube.com"
type = "website"
title = "Token Info Dashboard"

[[TOKENS.WEBLINKS]]
url = "https://twitter.com"
type = "socialmedia"
